name: copilot
description: 24h Copilot app.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  injectable: ^1.5.3
  json_annotation: ^4.6.0
  drift: ^2.0.2
  sqlite3_flutter_libs: ^0.5.9
  path_provider: ^2.0.11
  path: ^1.8.1

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.5.4
  mockito: ^5.2.0
  json_serializable: ^6.3.1
  drift_dev: ^2.0.1

flutter:
  uses-material-design: true
