name: copilot
description: 24h Copilot app.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  awesome_notifications: ^0.7.4+1
  bloc_test: ^9.1.0
  category_navigator: ^1.1.6
  cloud_firestore: ^4.5.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dotted_line: ^3.1.0
  drift: ^2.0.2
  email_validator: ^2.1.17
  equatable: ^2.0.3
  firebase_auth: ^4.4.0
  firebase_core: ^2.8.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_dialogs: ^3.0.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.1.4
  fluttertoast: ^8.2.1
  get_it: ^7.2.0
  hive_flutter: ^1.1.0
  injectable: ^2.1.0
  intl: any
  json_annotation: ^4.6.0
  path: ^1.8.2
  path_provider: ^2.0.12
  pie_chart: ^5.3.2
  sealed_flutter_bloc: ^8.0.0
  sqlite3_flutter_libs: ^0.5.12
  top_snackbar_flutter: ^3.0.0+1
  url_launcher: ^6.1.9

dev_dependencies:
  build_runner: ^2.2.0
  drift_dev: ^2.0.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  injectable_generator: ^2.1.3
  json_serializable: ^6.3.1
  mockito: ^5.3.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/edit_mode.svg
