name: copilot
description: 24h Copilot app.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  awesome_notifications: ^0.7.5-dev.3
  bloc_test: ^9.1.0
  category_navigator: ^1.1.6
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dotted_line: ^3.1.0
  drift: ^2.0.2
  easy_search_bar: ^2.5.0
  email_validator: ^2.1.17
  equatable: ^2.0.3
  flex_color_scheme: ^7.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_colorpicker: ^1.0.3
  flutter_dialogs: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.7
  flutter_time_picker_spinner: ^2.0.0
  get: ^4.6.5
  get_it: ^7.2.0
  hive_flutter: ^1.1.0
  injectable: ^2.1.0
  intl: any
  json_annotation: ^4.6.0
  path: ^1.8.2
  path_provider: ^2.0.12
  pie_chart: ^5.3.2
  sealed_flutter_bloc: ^8.0.0
  sqlite3_flutter_libs: ^0.5.12
  top_snackbar_flutter: ^3.0.0+1
  url_launcher: ^6.1.9

dev_dependencies:
  build_runner: ^2.2.0
  drift_dev: ^2.0.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  injectable_generator: ^2.1.3
  json_serializable: ^6.3.1
  mockito: ^5.3.0

# Because every version of flutter_localization depends on flutter_localizations from sdk which depends on intl 0.18.0,
# every version of flutter_localization requires intl 0.18.0.
# And because awesome_notifications >=0.7.4+1 depends on intl ^0.18.1, flutter_localization is incompatible
# with awesome_notifications >=0.7.4+1.
dependency_overrides:
  intl: ^0.18.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/edit_mode.svg
    - assets/illustrations/
